### ISSUE TITLE
Species dropdown isn't properly populated

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/GenotifyDesktop#20]
Trying to populate the species dropdown on page load so that users can select one or more species to limit searches to. While the code in the `populateDropdown` function works just fine (when called on dummy elements from `newQuery`, for example), I can't get the code to actually run on page load. It will likely have performance issues, but will deal with that when I come to it.

A searchable, multi-selectable datalist would probably be preferable, maybe this is a better solution: http://projects.sergiodinislopes.pt/flexdatalist/

Can search a `JSON` file directly, without need for loading. Would have to restructure the file a bit, but it might be worth a look.

**Comment by luistangui** [comment]
Hi @j-andrews, Can you assign it to me?

**Comment by j-andrews7** [comment]
Hi @luistangui, I actually continued working on this some last night and expect to have it resolved today. You are always welcome to submit a pull request for any of the other issues though!

I have to ask, how did you find this project?

**Comment by j-andrews7** [comment]
48f94d6 partially resolved this - it just can't handle searching a 20 MB species file. Will have to parse it down a bit.

**Comment by j-andrews7** [comment]
d21503e fully resolved this. Parsed down file. Now excludes a lot of the millions of types of bacteria, but should still have any species anybody should want. Also trivial to add new ones.
